version: "3.3"
services:
  database:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=card_management_system_database
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data/

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper


  card-mangegment-system:
    image: card-mangegment-system
    depends_on:
      - database
      - kafka
    ports:
      - 8081:8081

  notification-system:
    image: notification-system
    depends_on:
      - kafka
    ports:
      - 8080:8080